package com.liquidskr.btclient

object Constansts {
    enum class BluetoothExceptionType{
        DEFAULT_EXCEPTION,
        PERMISSION_MISSING,
        NO_PAIRED_DEVICE,
        CONNECTION_FAILED,
        DATABASE_HELPER_NOT_INITIALIZED,
        SQLITE_EXCEPTION,
        EXTERNAL_DATABASE_PERMISSION_MISSING,
        DISCONNECTED,
        IO_EXCEPTION,
    }
    enum class BluetoothMessageType {
        MEMBERSHIP_ALL,
        MEMBERSHIP_ALL_COUNT,
        TOOL_ALL,
        TOOL_ALL_COUNT,
        RENTAL_REQUEST_SHEET_PAGE_BY_TOOLBOX,
        RENTAL_REQUEST_SHEET_LIST_BY_TOOLBOX,
        RENTAL_SHEET_PAGE_BY_MEMBERSHIP,
        RETURN_SHEET_PAGE_BY_MEMBERSHIP,
        OUTSTANDING_RENTAL_SHEET_PAGE_BY_MEMBERSHIP,
        OUTSTANDING_RENTAL_SHEET_LIST_BY_MEMBERSHIP,
        OUTSTANDING_RENTAL_SHEET_PAGE_BY_TOOLBOX,
        OUTSTANDING_RENTAL_SHEET_LIST_BY_TOOLBOX,
        RENTAL_REQUEST_SHEET_FORM,
        RENTAL_REQUEST_SHEET_APPROVE,
        RETURN_SHEET_FORM,
        TOOLBOX_TOOL_LABEL_FORM,
        RETURN_SHEET_REQUEST,
        TAG_FORM,
        TOOLBOX_TOOL_LABEL,
        TAG_LIST,
        TAG_ALL,
        TOOLBOX_TOOL_LABEL_ALL,
        TAG_GROUP,
        OUTSTANDING_RENTAL_SHEET_BY_TAG, TAG_ALL_COUNT,
        TOOLBOX_TOOL_LABEL_ALL_COUNT,
        TAG, RENTAL_REQUEST_SHEET_APPROVE_STANDBY,
        RENTAL_REQUEST_SHEET_FORM_STANDBY,
        RETURN_SHEET_FORM_STANDBY,
        RENTAL_REQUEST_SHEET_CANCEL,
        RENTAL_REQUEST_SHEET_READY_PAGE_BY_MEMBERSHIP,
        OUTSTANDING_RENTAL_SHEET_PAGE_BY_MEMBERSHIP_COUNT,
        RENTAL_REQUEST_SHEET_READY_PAGE_BY_MEMBERSHIP_COUNT,
        OUTSTANDING_RENTAL_SHEET_PAGE_BY_TOOLBOX_COUNT,
        RENTAL_REQUEST_SHEET_PAGE_BY_TOOLBOX_COUNT,
        RENTAL_REQUEST_SHEET_APPLY,
        TAG_AND_TOOLBOX_TOOL_LABEL_FORM,
        TAG_AND_TOOLBOX_TOOL_LABEL,
        OUTSTANDING_RENTAL_SHEET_PAGE_ALL_COUNT,
        OUTSTANDING_RENTAL_SHEET_PAGE_ALL,
        TOOLBOX_ALL,

        TEST,

    }

    const val COMMUNICATION_TIMEOUT = 10000 //10초
    const val BLUETOOTH_MAX_CHUNK_LENGTH = 1024
    const val INTEGER_BYTE_SIZE = 4
}