package com.care4u.constant;

public enum RequestType {
    MEMBERSHIP_ALL,
    TOOL_ALL,
    RENTAL_REQUEST_SHEET_PAGE_BY_TOOLBOX,
    RENTAL_SHEET_PAGE_BY_MEMBERSHIP,
    RETURN_SHEET_PAGE_BY_MEMBERSHIP,
    OUTSTANDING_RENTAL_SHEET_PAGE_BY_MEMBERSHIP,
    OUTSTANDING_RENTAL_SHEET_PAGE_BY_TOOLBOX,
}
