package com.care4u.constant;

public enum RequestType {
	MEMBERSHIP_ALL,
    MEMBERSHIP_ALL_COUNT,
    TOOL_ALL,
    TOOL_ALL_COUNT,
    RENTAL_REQUEST_SHEET_PAGE_BY_TOOLBOX,
    RENTAL_REQUEST_SHEET_LIST_BY_TOOLBOX,
    RENTAL_SHEET_PAGE_BY_MEMBERSHIP,
    RETURN_SHEET_PAGE_BY_MEMBERSHIP,
    OUTSTANDING_RENTAL_SHEET_PAGE_BY_MEMBERSHIP,
    OUTSTANDING_RENTAL_SHEET_LIST_BY_MEMBERSHIP,
    OUTSTANDING_RENTAL_SHEET_PAGE_BY_TOOLBOX,
    OUTSTANDING_RENTAL_SHEET_LIST_BY_TOOLBOX,
    RENTAL_REQUEST_SHEET_FORM,
    RENTAL_REQUEST_SHEET_APPROVE,
    RETURN_SHEET_FORM,
    TOOLBOX_TOOL_LABEL_FORM,
    RETURN_SHEET_REQUEST,
    TAG_FORM,
    TOOLBOX_TOOL_LABEL,
    TAG_LIST,
    TAG_ALL,
    TOOLBOX_TOOL_LABEL_ALL,
    TAG_GROUP,
    OUTSTANDING_RENTAL_SHEET_BY_TAG, TAG_ALL_COUNT, TOOLBOX_TOOL_LABEL_ALL_COUNT
}
